services:
  database:
      image: postgres:alpine
      container_name: database
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      networks:
        - db_net
      volumes:
        - database:/var/lib/postgresql/data
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.role == manager]
  web-ui:
    image: dpage/pgadmin4:latest
    container_name: web-ui
    ports:
      - "5050:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - db_net
    volumes:
      - webui:/var/lib/pgadmin
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  db_net:
    name: db_net
    external: true
volumes:
    webui: {}
    database: {}